--1. ĐÊM SỐ LƯỢNG KHÁCH HÀNG MỞ MỚI TÀI KHOẢN CỦA MỖI CHI NHÁNH TRỌNG NĂM 2024.
SELECT COUNT(DISTINCT KH.MA_KHACHHANG), CN.MA_CHINHANH, CN.TEN_CHINHANH FROM KHACHHANG KH 
INNER JOIN CHINHANH CN ON CN.MA_CHINHANH = KH.MA_CHINHANH
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN < '2024-01-01'
)
GROUP BY  CN.MA_CHINHANH, CN.TEN_CHINHANH

--2. PHÂN TÍCH CƠ CẤU NGÀNH NGHỀ CỦA KHÁCH HÀNG MỞ MỚI TÀI KHOẢN GIAI ĐOẠN 2022-2024.
SELECT CAP1.TEN_NGANHNGHE_KINHTE_CAP01,
COUNT(DISTINCT KH.MA_KHACHHANG) AS SO_KHACH,
ROUND(COUNT(DISTINCT KH.MA_KHACHHANG) * 100.0 / SUM(COUNT(DISTINCT KH.MA_KHACHHANG)) OVER(),2) AS TY_TRONG_PCT FROM KHACHHANG KH 
INNER JOIN NGANHNGHE_KINHTE_CAP03 CAP3 ON CAP3.MA_NGANHNGHE_KINHTE_CAP03 = KH.MA_NGANHNGHE_KINHTE
INNER JOIN NGANHNGHE_KINHTE_CAP02 CAP2 ON CAP2.MA_NGANHNGHE_KINHTE_CAP02 = CAP3.MA_NGANHNGHE_KINHTE_CAP02
INNER JOIN NGANHNGHE_KINHTE_CAP01 CAP1 ON CAP1.MA_NGANHNGHE_KINHTE_CAP01 = CAP2.MA_NGANHNGHE_KINHTE_CAP01
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) BETWEEN 2022 AND 2024
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN < '2022-01-01'
)
GROUP BY CAP1.TEN_NGANHNGHE_KINHTE_CAP01
ORDER BY TY_TRONG_PCT DESC

--3. LẬP DANH SÁCH 02 CHI NHÁNH CÓ NHIỀU HÀNG MỞ TÀI KHOẢN MỚI NHẤT TRONG QUÝ I/2024.
WITH CTE AS(
SELECT COUNT(DISTINCT KH.MA_KHACHHANG) AS SO_LG_KHACH_HANG, CN.MA_CHINHANH, CN.TEN_CHINHANH,
RANK() OVER(ORDER BY COUNT(DISTINCT KH.MA_KHACHHANG) DESC) AS STT
FROM KHACHHANG KH 
INNER JOIN CHINHANH CN ON CN.MA_CHINHANH = KH.MA_CHINHANH
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024 AND DATEPART(QUARTER, KH.NGAY_MO_TAIKHOAN) = 1
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN < '2024-01-01'
)
GROUP BY  CN.MA_CHINHANH, CN.TEN_CHINHANH)

SELECT * FROM CTE 
WHERE STT <= 2

--4. LẬP DANH SÁCH CÁC DOANH NGHIỆP TƯ NHÂN MỞ TÀI KHOẢN TRỌNG NĂM 2024.
SELECT * FROM KHACHHANG KH 
INNER JOIN LOAIHINH_DOANHNGHIEP DN ON DN.MA_LOAIHINH_DOANHNGHIEP = KH.MA_LOAIHINH_KHACHHANG
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024 AND DN.TEN_LOAIHINH_DOANHNGHIEP LIKE N'%tư nhân%'

--5. ĐẾM SỐ LƯỢNG KHÁCH HÀNG MỞ MỚI TÀI KHOẢN CỦA MỖI KHU VỰC TRỌNG 02 QUÝ CÔNG NĂM 2024.
SELECT COUNT(DISTINCT KH.MA_KHACHHANG), KV.MA_KHUVUC,KV.TEN_KHUVUC FROM KHACHHANG KH 
INNER JOIN CHINHANH CN ON CN.MA_CHINHANH = KH.MA_CHINHANH
INNER JOIN KHUVUC KV ON KV.MA_KHUVUC = CN.MA_KHUVUC
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN < '2024-01-01'
)
GROUP BY  KV.MA_KHUVUC,KV.TEN_KHUVUC

-------------------------------------------------------------------------------------------------------------------------
--TIÊU CHÍ BÁO CÁO SỐ LG KHÁCH HÀNG
SELECT COUNT(DISTINCT KH.MA_KHACHHANG) AS LUY_KE_2023
FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31'

SELECT COUNT(DISTINCT KH.MA_KHACHHANG) FROM KHACHHANG KH
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024 
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG
FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31')

SELECT COUNT(DISTINCT KH.MA_KHACHHANG) AS LUY_KE_2023
FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31'

--LOẠI KHÁCH HÀNG
SELECT KH.MA_LOAI_KHACHHANG, COUNT(DISTINCT KH.MA_KHACHHANG) AS LUY_KE_2023
FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31'
GROUP BY KH.MA_LOAI_KHACHHANG

SELECT KH.MA_LOAI_KHACHHANG, COUNT(DISTINCT KH.MA_KHACHHANG) FROM KHACHHANG KH
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024 
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG
FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31')
GROUP BY KH.MA_LOAI_KHACHHANG

SELECT KH.MA_LOAI_KHACHHANG, COUNT(DISTINCT KH.MA_KHACHHANG) AS LUY_KE_2023
FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31'
GROUP BY KH.MA_LOAI_KHACHHANG

-----------------------------------------------------------------------------------------------------------------------------------
--LOẠI HÌNH DOANH NGHIỆP
SELECT COUNT(DN.MA_LOAIHINH_DOANHNGHIEP) FROM KHACHHANG KH 
INNER JOIN LOAIHINH_DOANHNGHIEP DN ON DN.MA_LOAIHINH_DOANHNGHIEP = KH.MA_LOAIHINH_KHACHHANG
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31' AND DN.TEN_LOAIHINH_DOANHNGHIEP LIKE N'%tư nhân%' AND MA_LOAI_KHACHHANG = 'TC'

SELECT COUNT(DN.MA_LOAIHINH_DOANHNGHIEP) FROM KHACHHANG KH 
INNER JOIN LOAIHINH_DOANHNGHIEP DN ON DN.MA_LOAIHINH_DOANHNGHIEP = KH.MA_LOAIHINH_KHACHHANG
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024 AND DN.TEN_LOAIHINH_DOANHNGHIEP LIKE N'%tư nhân%' AND MA_LOAI_KHACHHANG = 'TC'
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31')

SELECT COUNT(DN.MA_LOAIHINH_DOANHNGHIEP) FROM KHACHHANG KH 
INNER JOIN LOAIHINH_DOANHNGHIEP DN ON DN.MA_LOAIHINH_DOANHNGHIEP = KH.MA_LOAIHINH_KHACHHANG
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31' AND DN.TEN_LOAIHINH_DOANHNGHIEP LIKE N'%tư nhân%' AND MA_LOAI_KHACHHANG = 'TC'

--CÁ NHÂN
SELECT COUNT(DISTINCT KH.MA_KHACHHANG) FROM KHACHHANG KH 
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31' AND MA_LOAI_KHACHHANG = 'CN'

SELECT COUNT(DISTINCT KH.MA_KHACHHANG) FROM KHACHHANG KH 
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024 AND MA_LOAI_KHACHHANG = 'CN'
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31')

SELECT COUNT(DISTINCT KH.MA_KHACHHANG) FROM KHACHHANG KH 
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31' AND MA_LOAI_KHACHHANG = 'CN'

--KHÁC
SELECT COUNT(DN.MA_LOAIHINH_DOANHNGHIEP) FROM KHACHHANG KH 
INNER JOIN LOAIHINH_DOANHNGHIEP DN ON DN.MA_LOAIHINH_DOANHNGHIEP = KH.MA_LOAIHINH_KHACHHANG
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31' AND DN.TEN_LOAIHINH_DOANHNGHIEP NOT LIKE N'%tư nhân%' AND MA_LOAI_KHACHHANG = 'TC'

SELECT COUNT(DN.MA_LOAIHINH_DOANHNGHIEP) FROM KHACHHANG KH 
INNER JOIN LOAIHINH_DOANHNGHIEP DN ON DN.MA_LOAIHINH_DOANHNGHIEP = KH.MA_LOAIHINH_KHACHHANG
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024 AND DN.TEN_LOAIHINH_DOANHNGHIEP NOT LIKE N'%tư nhân%' AND MA_LOAI_KHACHHANG = 'TC'
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31')

SELECT COUNT(DN.MA_LOAIHINH_DOANHNGHIEP) FROM KHACHHANG KH 
INNER JOIN LOAIHINH_DOANHNGHIEP DN ON DN.MA_LOAIHINH_DOANHNGHIEP = KH.MA_LOAIHINH_KHACHHANG
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31' AND DN.TEN_LOAIHINH_DOANHNGHIEP NOT LIKE N'%tư nhân%' AND MA_LOAI_KHACHHANG = 'TC'
---------------------------------------------------------------------------------------------------------------------------------------
--NGÀNH NGHỀ KTE CẤP 1
--NÔNG LÂM,....
SELECT COUNT(DISTINCT MA_KHACHHANG) FROM KHACHHANG KH
INNER JOIN NGANHNGHE_KINHTE_CAP03 CAP3 ON CAP3.MA_NGANHNGHE_KINHTE_CAP03 = KH.MA_NGANHNGHE_KINHTE
INNER JOIN NGANHNGHE_KINHTE_CAP02 CAP2 ON CAP2.MA_NGANHNGHE_KINHTE_CAP02 = CAP3.MA_NGANHNGHE_KINHTE_CAP02
INNER JOIN NGANHNGHE_KINHTE_CAP01 CAP1 ON CAP1.MA_NGANHNGHE_KINHTE_CAP01 = CAP2.MA_NGANHNGHE_KINHTE_CAP01
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31' AND CAP1.MA_NGANHNGHE_KINHTE_CAP01 = 'A'

SELECT COUNT(DISTINCT MA_KHACHHANG) FROM KHACHHANG KH
INNER JOIN NGANHNGHE_KINHTE_CAP03 CAP3 ON CAP3.MA_NGANHNGHE_KINHTE_CAP03 = KH.MA_NGANHNGHE_KINHTE
INNER JOIN NGANHNGHE_KINHTE_CAP02 CAP2 ON CAP2.MA_NGANHNGHE_KINHTE_CAP02 = CAP3.MA_NGANHNGHE_KINHTE_CAP02
INNER JOIN NGANHNGHE_KINHTE_CAP01 CAP1 ON CAP1.MA_NGANHNGHE_KINHTE_CAP01 = CAP2.MA_NGANHNGHE_KINHTE_CAP01
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024 AND CAP1.MA_NGANHNGHE_KINHTE_CAP01 = 'A'
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31'
)

SELECT COUNT(DISTINCT MA_KHACHHANG) FROM KHACHHANG KH
INNER JOIN NGANHNGHE_KINHTE_CAP03 CAP3 ON CAP3.MA_NGANHNGHE_KINHTE_CAP03 = KH.MA_NGANHNGHE_KINHTE
INNER JOIN NGANHNGHE_KINHTE_CAP02 CAP2 ON CAP2.MA_NGANHNGHE_KINHTE_CAP02 = CAP3.MA_NGANHNGHE_KINHTE_CAP02
INNER JOIN NGANHNGHE_KINHTE_CAP01 CAP1 ON CAP1.MA_NGANHNGHE_KINHTE_CAP01 = CAP2.MA_NGANHNGHE_KINHTE_CAP01
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31' AND CAP1.MA_NGANHNGHE_KINHTE_CAP01 = 'A'

--KHAI KHOÁNG
SELECT COUNT(DISTINCT MA_KHACHHANG) FROM KHACHHANG KH
INNER JOIN NGANHNGHE_KINHTE_CAP03 CAP3 ON CAP3.MA_NGANHNGHE_KINHTE_CAP03 = KH.MA_NGANHNGHE_KINHTE
INNER JOIN NGANHNGHE_KINHTE_CAP02 CAP2 ON CAP2.MA_NGANHNGHE_KINHTE_CAP02 = CAP3.MA_NGANHNGHE_KINHTE_CAP02
INNER JOIN NGANHNGHE_KINHTE_CAP01 CAP1 ON CAP1.MA_NGANHNGHE_KINHTE_CAP01 = CAP2.MA_NGANHNGHE_KINHTE_CAP01
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31' AND CAP1.MA_NGANHNGHE_KINHTE_CAP01 = 'B'

SELECT COUNT(DISTINCT MA_KHACHHANG) FROM KHACHHANG KH
INNER JOIN NGANHNGHE_KINHTE_CAP03 CAP3 ON CAP3.MA_NGANHNGHE_KINHTE_CAP03 = KH.MA_NGANHNGHE_KINHTE
INNER JOIN NGANHNGHE_KINHTE_CAP02 CAP2 ON CAP2.MA_NGANHNGHE_KINHTE_CAP02 = CAP3.MA_NGANHNGHE_KINHTE_CAP02
INNER JOIN NGANHNGHE_KINHTE_CAP01 CAP1 ON CAP1.MA_NGANHNGHE_KINHTE_CAP01 = CAP2.MA_NGANHNGHE_KINHTE_CAP01
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024 AND CAP1.MA_NGANHNGHE_KINHTE_CAP01 = 'B'
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31')

SELECT COUNT(DISTINCT MA_KHACHHANG) FROM KHACHHANG KH
INNER JOIN NGANHNGHE_KINHTE_CAP03 CAP3 ON CAP3.MA_NGANHNGHE_KINHTE_CAP03 = KH.MA_NGANHNGHE_KINHTE
INNER JOIN NGANHNGHE_KINHTE_CAP02 CAP2 ON CAP2.MA_NGANHNGHE_KINHTE_CAP02 = CAP3.MA_NGANHNGHE_KINHTE_CAP02
INNER JOIN NGANHNGHE_KINHTE_CAP01 CAP1 ON CAP1.MA_NGANHNGHE_KINHTE_CAP01 = CAP2.MA_NGANHNGHE_KINHTE_CAP01
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31' AND CAP1.MA_NGANHNGHE_KINHTE_CAP01 = 'B'

--KHÁC
SELECT COUNT(DISTINCT MA_KHACHHANG) FROM KHACHHANG KH
INNER JOIN NGANHNGHE_KINHTE_CAP03 CAP3 ON CAP3.MA_NGANHNGHE_KINHTE_CAP03 = KH.MA_NGANHNGHE_KINHTE
INNER JOIN NGANHNGHE_KINHTE_CAP02 CAP2 ON CAP2.MA_NGANHNGHE_KINHTE_CAP02 = CAP3.MA_NGANHNGHE_KINHTE_CAP02
INNER JOIN NGANHNGHE_KINHTE_CAP01 CAP1 ON CAP1.MA_NGANHNGHE_KINHTE_CAP01 = CAP2.MA_NGANHNGHE_KINHTE_CAP01
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31' AND CAP1.MA_NGANHNGHE_KINHTE_CAP01 != 'B' 
AND CAP1.MA_NGANHNGHE_KINHTE_CAP01 != 'A'

SELECT COUNT(DISTINCT MA_KHACHHANG) FROM KHACHHANG KH
INNER JOIN NGANHNGHE_KINHTE_CAP03 CAP3 ON CAP3.MA_NGANHNGHE_KINHTE_CAP03 = KH.MA_NGANHNGHE_KINHTE
INNER JOIN NGANHNGHE_KINHTE_CAP02 CAP2 ON CAP2.MA_NGANHNGHE_KINHTE_CAP02 = CAP3.MA_NGANHNGHE_KINHTE_CAP02
INNER JOIN NGANHNGHE_KINHTE_CAP01 CAP1 ON CAP1.MA_NGANHNGHE_KINHTE_CAP01 = CAP2.MA_NGANHNGHE_KINHTE_CAP01
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024 AND CAP1.MA_NGANHNGHE_KINHTE_CAP01 != 'B' 
AND CAP1.MA_NGANHNGHE_KINHTE_CAP01 != 'A'
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31')

SELECT COUNT(DISTINCT MA_KHACHHANG) FROM KHACHHANG KH
INNER JOIN NGANHNGHE_KINHTE_CAP03 CAP3 ON CAP3.MA_NGANHNGHE_KINHTE_CAP03 = KH.MA_NGANHNGHE_KINHTE
INNER JOIN NGANHNGHE_KINHTE_CAP02 CAP2 ON CAP2.MA_NGANHNGHE_KINHTE_CAP02 = CAP3.MA_NGANHNGHE_KINHTE_CAP02
INNER JOIN NGANHNGHE_KINHTE_CAP01 CAP1 ON CAP1.MA_NGANHNGHE_KINHTE_CAP01 = CAP2.MA_NGANHNGHE_KINHTE_CAP01
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31' AND CAP1.MA_NGANHNGHE_KINHTE_CAP01 != 'B' 
AND CAP1.MA_NGANHNGHE_KINHTE_CAP01 != 'A'

-----------------------------------------------------------------------------------------------------------------------------------------------------------
--QUY MÔ DOANH NGHIỆP
SELECT 
CASE
	WHEN  KH.QUY_MO_DOANHNGHIEP < 50 THEN N'DƯỚI 50'
	WHEN KH.QUY_MO_DOANHNGHIEP BETWEEN 50 AND 100 THEN N'TỪ 50-100'
	ELSE N'TRÊN 100'
END AS QUY_MO, COUNT(DISTINCT KH.MA_KHACHHANG)
FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31' AND KH.MA_LOAI_KHACHHANG = 'TC'
GROUP BY 
CASE
	WHEN  KH.QUY_MO_DOANHNGHIEP < 50 THEN N'DƯỚI 50'
	WHEN KH.QUY_MO_DOANHNGHIEP BETWEEN 50 AND 100 THEN N'TỪ 50-100'
	ELSE N'TRÊN 100'
END

SELECT 
CASE
	WHEN  KH.QUY_MO_DOANHNGHIEP < 50 THEN N'DƯỚI 50'
	WHEN KH.QUY_MO_DOANHNGHIEP BETWEEN 50 AND 100 THEN N'TỪ 50-100'
	ELSE N'TRÊN 100'
END AS QUY_MO, COUNT(DISTINCT KH.MA_KHACHHANG)
FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31' AND KH.MA_LOAI_KHACHHANG = 'TC'
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31')
GROUP BY 
CASE
	WHEN  KH.QUY_MO_DOANHNGHIEP < 50 THEN N'DƯỚI 50'
	WHEN KH.QUY_MO_DOANHNGHIEP BETWEEN 50 AND 100 THEN N'TỪ 50-100'
	ELSE N'TRÊN 100'
END

SELECT 
CASE
	WHEN  KH.QUY_MO_DOANHNGHIEP < 50 THEN N'DƯỚI 50'
	WHEN KH.QUY_MO_DOANHNGHIEP BETWEEN 50 AND 100 THEN N'TỪ 50-100'
	ELSE N'TRÊN 100'
END AS QUY_MO, COUNT(DISTINCT KH.MA_KHACHHANG)
FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31' AND KH.MA_LOAI_KHACHHANG = 'TC'
GROUP BY 
CASE
	WHEN  KH.QUY_MO_DOANHNGHIEP < 50 THEN N'DƯỚI 50'
	WHEN KH.QUY_MO_DOANHNGHIEP BETWEEN 50 AND 100 THEN N'TỪ 50-100'
	ELSE N'TRÊN 100'
END

--------------------------------------------------------------------------------------------------------------------------------------------------------
--VỐN ĐIỀU LỆ
SELECT 
CASE
	WHEN  KH.VON_DIEULE < 1000000000 THEN N'DƯỚI 1 TỶ'
	WHEN KH.VON_DIEULE BETWEEN 1000000000 AND 5000000000 THEN N'TỪ 1 TỶ-5 TỶ'
	WHEN KH.VON_DIEULE BETWEEN 5000000000 AND 10000000000 THEN N'TỪ 5 TỶ-10 TỶ'
	ELSE N'TRÊN 10 TỶ'
END AS QUY_MO, COUNT(DISTINCT KH.MA_KHACHHANG)
FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31' AND KH.MA_LOAI_KHACHHANG = 'TC'
GROUP BY 
CASE
	WHEN  KH.VON_DIEULE < 1000000000 THEN N'DƯỚI 1 TỶ'
	WHEN KH.VON_DIEULE BETWEEN 1000000000 AND 5000000000 THEN N'TỪ 1 TỶ-5 TỶ'
	WHEN KH.VON_DIEULE BETWEEN 5000000000 AND 10000000000 THEN N'TỪ 5 TỶ-10 TỶ'
	ELSE N'TRÊN 10 TỶ'
END

SELECT 
CASE
	WHEN  KH.VON_DIEULE < 1000000000 THEN N'DƯỚI 1 TỶ'
	WHEN KH.VON_DIEULE BETWEEN 1000000000 AND 5000000000 THEN N'TỪ 1 TỶ-5 TỶ'
	WHEN KH.VON_DIEULE BETWEEN 5000000000 AND 10000000000 THEN N'TỪ 5 TỶ-10 TỶ'
	ELSE N'TRÊN 10 TỶ'
END AS QUY_MO, COUNT(DISTINCT KH.MA_KHACHHANG)
FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31' AND KH.MA_LOAI_KHACHHANG = 'TC'
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31')
GROUP BY 
CASE
	WHEN  KH.VON_DIEULE < 1000000000 THEN N'DƯỚI 1 TỶ'
	WHEN KH.VON_DIEULE BETWEEN 1000000000 AND 5000000000 THEN N'TỪ 1 TỶ-5 TỶ'
	WHEN KH.VON_DIEULE BETWEEN 5000000000 AND 10000000000 THEN N'TỪ 5 TỶ-10 TỶ'
	ELSE N'TRÊN 10 TỶ'
END

SELECT 
CASE
	WHEN  KH.VON_DIEULE < 1000000000 THEN N'DƯỚI 1 TỶ'
	WHEN KH.VON_DIEULE BETWEEN 1000000000 AND 5000000000 THEN N'TỪ 1 TỶ-5 TỶ'
	WHEN KH.VON_DIEULE BETWEEN 5000000000 AND 10000000000 THEN N'TỪ 5 TỶ-10 TỶ'
	ELSE N'TRÊN 10 TỶ'
END AS QUY_MO, COUNT(DISTINCT KH.MA_KHACHHANG)
FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31' AND KH.MA_LOAI_KHACHHANG = 'TC'
GROUP BY 
CASE
	WHEN  KH.VON_DIEULE < 1000000000 THEN N'DƯỚI 1 TỶ'
	WHEN KH.VON_DIEULE BETWEEN 1000000000 AND 5000000000 THEN N'TỪ 1 TỶ-5 TỶ'
	WHEN KH.VON_DIEULE BETWEEN 5000000000 AND 10000000000 THEN N'TỪ 5 TỶ-10 TỶ'
	ELSE N'TRÊN 10 TỶ'
END

----------------------------------------------------------------------------------------------------------------------------------------------------------------
--KHU VỰC
SELECT COUNT(DISTINCT KH.MA_KHACHHANG) FROM KHACHHANG KH 
INNER JOIN CHINHANH CN ON CN.MA_CHINHANH = KH.MA_CHINHANH
INNER JOIN KHUVUC KV ON KV.MA_KHUVUC = CN.MA_KHUVUC
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31'
AND KV.MA_KHUVUC BETWEEN 'A01' AND 'A06'

SELECT COUNT(DISTINCT KH.MA_KHACHHANG) FROM KHACHHANG KH 
INNER JOIN CHINHANH CN ON CN.MA_CHINHANH = KH.MA_CHINHANH
INNER JOIN KHUVUC KV ON KV.MA_KHUVUC = CN.MA_KHUVUC
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024
AND KV.MA_KHUVUC BETWEEN 'A01' AND 'A06'
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31')

SELECT COUNT(DISTINCT KH.MA_KHACHHANG) FROM KHACHHANG KH 
INNER JOIN CHINHANH CN ON CN.MA_CHINHANH = KH.MA_CHINHANH
INNER JOIN KHUVUC KV ON KV.MA_KHUVUC = CN.MA_KHUVUC
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31'
AND KV.MA_KHUVUC BETWEEN 'A01' AND 'A06'

------------------------------------------------------------------------------------------------------------
SELECT COUNT(DISTINCT KH.MA_KHACHHANG) FROM KHACHHANG KH 
INNER JOIN CHINHANH CN ON CN.MA_CHINHANH = KH.MA_CHINHANH
INNER JOIN KHUVUC KV ON KV.MA_KHUVUC = CN.MA_KHUVUC
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31'
AND KV.MA_KHUVUC BETWEEN 'A07' AND 'A08'

SELECT COUNT(DISTINCT KH.MA_KHACHHANG) FROM KHACHHANG KH 
INNER JOIN CHINHANH CN ON CN.MA_CHINHANH = KH.MA_CHINHANH
INNER JOIN KHUVUC KV ON KV.MA_KHUVUC = CN.MA_KHUVUC
WHERE YEAR(KH.NGAY_MO_TAIKHOAN) = 2024
AND KV.MA_KHUVUC BETWEEN 'A07' AND 'A08'
AND KH.MA_KHACHHANG NOT IN (
SELECT DISTINCT KH.MA_KHACHHANG FROM KHACHHANG KH
WHERE KH.NGAY_MO_TAIKHOAN <= '2023-12-31')

SELECT COUNT(DISTINCT KH.MA_KHACHHANG) FROM KHACHHANG KH 
INNER JOIN CHINHANH CN ON CN.MA_CHINHANH = KH.MA_CHINHANH
INNER JOIN KHUVUC KV ON KV.MA_KHUVUC = CN.MA_KHUVUC
WHERE KH.NGAY_MO_TAIKHOAN <= '2024-12-31'
AND KV.MA_KHUVUC BETWEEN 'A07' AND 'A08'