--1.
--ĐẦU KỲ
SELECT COUNT(SA.SAVING_ACC_ID) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE <= '2023-12-31'
AND SA.SAVE_END_DATE > '2023-12-31'

--MỞ MỚI QUÝ 1/2024
SELECT COUNT(SA.SAVING_ACC_ID) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER,SA.SAVE_DATE) = 1 AND YEAR(SA.SAVE_DATE) = 2024
--TẤT TOÁN QUÝ 1/2024
SELECT COUNT(SA.SAVING_ACC_ID) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER,SA.SAVE_END_DATE) = 1 AND YEAR(SA.SAVE_END_DATE) = 2024

--MỞ MỚI QUÝ 2/2024
SELECT COUNT(SA.SAVING_ACC_ID) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER,SA.SAVE_DATE) = 2 AND YEAR(SA.SAVE_DATE) = 2024
--TẤT TOÁN QUÝ 2/2024
SELECT COUNT(SA.SAVING_ACC_ID) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER,SA.SAVE_END_DATE) = 2 AND YEAR(SA.SAVE_END_DATE) = 2024

--CUỐI KỲ
SELECT COUNT(SA.SAVING_ACC_ID) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE <= '2024-06-30'
AND SA.SAVE_END_DATE > '2024-06-30'
---------------------------------------------------------------------------------
--2. SỐ LG KHÁCH
--ĐẦU KỲ
SELECT COUNT(DISTINCT SA.CUSTID) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE <= '2023-12-31'
AND SA.SAVE_END_DATE > '2023-12-31'

--MỞ MỚI QUÝ 1/2024
SELECT COUNT(DISTINCT SA.CUSTID) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER, SA.SAVE_DATE) = 1 AND YEAR(SA.SAVE_DATE) = 2024
AND SA.CUSTID NOT IN 
(SELECT DISTINCT SA.CUSTID FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE <= '2023-12-31'
AND SA.SAVE_END_DATE > '2023-12-31')

--TẤT TOÁN QUÝ 1/2024
SELECT COUNT(DISTINCT SA.CUSTID) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER, SA.SAVE_END_DATE)  = 1 AND YEAR(SA.SAVE_END_DATE ) = 2024
AND SA.CUSTID NOT IN 
(SELECT DISTINCT SA.CUSTID
FROM SAVING_ACCOUNT SA
WHERE SAVE_DATE <= '2024-03-31' AND SAVE_END_DATE > '2024-03-31')

--MỞ MỚI QUÝ 2/2024 -  --Cuối kỳ Q1 sẽ là đầu kỳ Q2
SELECT COUNT(DISTINCT SA.CUSTID) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER, SA.SAVE_DATE) = 2 AND YEAR(SA.SAVE_DATE) = 2024 
AND SA.CUSTID NOT IN
(SELECT DISTINCT SA.CUSTID 
FROM SAVING_ACCOUNT SA
WHERE SAVE_DATE <= '2024-03-31'AND SAVE_END_DATE > '2024-03-31') 

--TẤT TOÁN QUÝ 2/2024
SELECT COUNT(DISTINCT SA.CUSTID) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER, SA.SAVE_END_DATE)  = 2 AND YEAR(SA.SAVE_END_DATE ) = 2024
AND SA.CUSTID NOT IN 
(SELECT DISTINCT SA.CUSTID
FROM SAVING_ACCOUNT
WHERE SAVE_DATE <= '2024-06-30' AND SAVE_END_DATE > '2024-06-30')

--CUỐI KỲ
SELECT COUNT(DISTINCT SA.CUSTID) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE <= '2024-06-30'
AND SA.SAVE_END_DATE > '2024-06-30'

-----------------------------------------------------------------------------------------------------------
--ĐẦU KỲ
SELECT SUM(SA.SAV_AMOUNT) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE <= '2023-12-31'
AND SA.SAVE_END_DATE > '2023-12-31'

--MỞ MỚI QUÝ 1/2024
SELECT SUM(SA.SAV_AMOUNT) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER,SA.SAVE_DATE) = 1 AND YEAR(SA.SAVE_DATE) = 2024
--TẤT TOÁN QUÝ 1/2024
SELECT SUM(SA.SAV_AMOUNT) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER,SA.SAVE_END_DATE) = 1 AND YEAR(SA.SAVE_END_DATE) = 2024

--MỞ MỚI QUÝ 2/2024
SELECT SUM(SA.SAV_AMOUNT) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER,SA.SAVE_DATE) = 2 AND YEAR(SA.SAVE_DATE) = 2024
--TẤT TOÁN QUÝ 2/2024
SELECT SUM(SA.SAV_AMOUNT) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER,SA.SAVE_END_DATE) = 2 AND YEAR(SA.SAVE_END_DATE) = 2024

--CUỐI KỲ
SELECT SUM(SA.SAV_AMOUNT) FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE <= '2024-06-30'
AND SA.SAVE_END_DATE > '2024-06-30'

-----------------------------------------------------------------------------------------------------------
--CÁC KHOẢN TẤT TOÁN TRONG NĂM 2024
SELECT SUM(SA.SAV_AMOUNT) AS 'TONG_GOC', ROUND(SUM(SA.SAV_AMOUNT*SA.INTEREST*DATEDIFF(DAY, SA.SAVE_DATE, SA.SAVE_END_DATE)/36500),0) 'TONG_LAI' FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER,SA.SAVE_END_DATE) = 1 AND YEAR(SA.SAVE_END_DATE) = 2024

SELECT SUM(SA.SAV_AMOUNT) AS 'TONG_GOC', ROUND(SUM(SA.SAV_AMOUNT*SA.INTEREST*DATEDIFF(DAY, SA.SAVE_DATE, SA.SAVE_END_DATE)/36500),0) 'TONG_LAI' FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER,SA.SAVE_END_DATE) = 2 AND YEAR(SA.SAVE_END_DATE) = 2024

SELECT SUM(SA.SAV_AMOUNT) AS 'TONG_GOC', ROUND(SUM(SA.SAV_AMOUNT*SA.INTEREST*DATEDIFF(DAY, SA.SAVE_DATE, SA.SAVE_END_DATE)/36500),0) 'TONG_LAI' FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER,SA.SAVE_END_DATE) = 3 AND YEAR(SA.SAVE_END_DATE) = 2024

SELECT SUM(SA.SAV_AMOUNT) AS 'TONG_GOC', ROUND(SUM(SA.SAV_AMOUNT*SA.INTEREST*DATEDIFF(DAY, SA.SAVE_DATE, SA.SAVE_END_DATE)/36500),0) 'TONG_LAI' FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER,SA.SAVE_END_DATE) = 4 AND YEAR(SA.SAVE_END_DATE) = 2024

--------------------------------------------------------------------------------------------------------------
--PHÂN LOẠI THEO TIÊU CHÍ
SELECT 
CASE
	WHEN SA.SAV_AMOUNT < 1000000000 THEN N'DƯỚI 1 TỶ'
	WHEN SA.SAV_AMOUNT >= 1000000000 AND SA.SAV_AMOUNT < 10000000000 THEN N'TỪ 1 ĐẾN DƯỚI 10 TỶ'
	WHEN SA.SAV_AMOUNT >= 10000000000 AND SA.SAV_AMOUNT < 50000000000 THEN N'TỪ 10 ĐẾN DƯỚI 50 TỶ'
	WHEN SA.SAV_AMOUNT >= 50000000000 THEN N'TỪ 50 TỶ TRỞ LÊN'
END AS LOAI, COUNT(SA.SAVING_ACC_ID) AS SO_KHOAN, SUM(SA.SAV_AMOUNT) AS SO_TIEN
FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE BETWEEN '2024-01-01' AND '2024-06-30'
GROUP BY 
CASE
	WHEN SA.SAV_AMOUNT < 1000000000 THEN N'DƯỚI 1 TỶ'
	WHEN SA.SAV_AMOUNT >= 1000000000 AND SA.SAV_AMOUNT < 10000000000 THEN N'TỪ 1 ĐẾN DƯỚI 10 TỶ'
	WHEN SA.SAV_AMOUNT >= 10000000000 AND SA.SAV_AMOUNT < 50000000000 THEN N'TỪ 10 ĐẾN DƯỚI 50 TỶ'
	WHEN SA.SAV_AMOUNT >= 50000000000 THEN N'TỪ 50 TỶ TRỞ LÊN'
END 