--VỀ QUY MÔ TÍN DỤNG
--KỲ ĐẦU 31/12/2023
SELECT COUNT(CC.DEBID), SUM(CC.CR_AMOUNT) FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE CC.CR_CONTRACT_DATE <= '2023-12-31'
AND CC.CR_CONTRACT_END_DATE > '2023-12-31'

--QUÝ 1/2024
--PST
SELECT COUNT(CC.DEBID), SUM(CC.CR_AMOUNT) FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE DATEPART(QUARTER,CC.CR_CONTRACT_DATE) = 1 AND YEAR(CC.CR_CONTRACT_DATE) = 2024
--PSG
SELECT COUNT(CC.DEBID), SUM(CC.CR_AMOUNT) FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE DATEPART(QUARTER,CC.CR_CONTRACT_END_DATE) = 1 AND YEAR(CC.CR_CONTRACT_END_DATE) = 2024

--QUÝ 2/2024
--PST
SELECT COUNT(CC.DEBID), SUM(CC.CR_AMOUNT) FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE DATEPART(QUARTER,CC.CR_CONTRACT_DATE) = 2 AND YEAR(CC.CR_CONTRACT_DATE) = 2024
--PSG
SELECT COUNT(CC.DEBID), SUM(CC.CR_AMOUNT) FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE DATEPART(QUARTER,CC.CR_CONTRACT_END_DATE) = 2 AND YEAR(CC.CR_CONTRACT_END_DATE) = 2024

--KỲ CUỐI 30/06/2024
SELECT COUNT(CC.DEBID), SUM(CC.CR_AMOUNT) FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE CC.CR_CONTRACT_DATE <= '2024-06-30'
AND CC.CR_CONTRACT_END_DATE > '2024-06-30'

---------------------------------------------------------------------------------------------------------------------------------
--SỐ LG KHÁCH HÀNG
--KỲ ĐẦU 31/12/2023
SELECT COUNT(DISTINCT CC.CUSTID) FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE CC.CR_CONTRACT_DATE <= '2023-12-31'
AND CC.CR_CONTRACT_END_DATE > '2023-12-31'

--QUÝ 1/2024
--PST
SELECT COUNT(DISTINCT CC.CUSTID) FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE DATEPART(QUARTER, CC.CR_CONTRACT_DATE) = 1 AND YEAR(CC.CR_CONTRACT_DATE) = 2024
AND CC.CUSTID NOT IN (
SELECT DISTINCT CC.CUSTID FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE CC.CR_CONTRACT_DATE <= '2023-12-31'
AND CC.CR_CONTRACT_END_DATE > '2023-12-31')
--PSG
SELECT COUNT(DISTINCT CC.CUSTID) FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE DATEPART(QUARTER, CC.CR_CONTRACT_END_DATE) = 1 AND YEAR(CC.CR_CONTRACT_END_DATE) = 2024
AND CC.CUSTID NOT IN (
SELECT DISTINCT CC.CUSTID FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE CC.CR_CONTRACT_DATE <= '2024-03-31'
AND CC.CR_CONTRACT_END_DATE > '2024-03-31')

--QUÝ 2/2024
--PST
SELECT COUNT(DISTINCT CC.CUSTID) FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE DATEPART(QUARTER, CC.CR_CONTRACT_DATE) = 2 AND YEAR(CC.CR_CONTRACT_DATE) = 2024
AND CC.CUSTID NOT IN (
SELECT DISTINCT CC.CUSTID FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE CC.CR_CONTRACT_DATE <= '2024-03-31'
AND CC.CR_CONTRACT_END_DATE > '2024-03-31')
--PSG
SELECT COUNT(DISTINCT CC.CUSTID) FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE DATEPART(QUARTER, CC.CR_CONTRACT_END_DATE) = 2 AND YEAR(CC.CR_CONTRACT_END_DATE) = 2024
AND CC.CUSTID NOT IN (
SELECT DISTINCT CC.CUSTID FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE CC.CR_CONTRACT_DATE <= '2024-06-30'
AND CC.CR_CONTRACT_END_DATE > '2024-06-30')

--KỲ CUỐI 30/06/2024
SELECT COUNT(DISTINCT CC.CUSTID) FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
WHERE CC.CR_CONTRACT_DATE <= '2024-06-30'
AND CC.CR_CONTRACT_END_DATE > '2024-06-30'

-----------------------------------------------------------------------------------------------------------------------------------
--DƯ NỢ GỐC CÒN LẠI
--ĐẦU KỲ
WITH CTE AS(
SELECT CR.DEBID, SUM(CR.PRINCIPAL_AMOUNT) AS SO_TIEN_THU
FROM CUSTOMER_REPAYMENT CR
WHERE CR.PAYMENT_DATE <= '2023-12-31'
GROUP BY CR.DEBID)

SELECT SUM(CC.CR_AMOUNT - ISNULL(A.SO_TIEN_THU,0)) FROM CREDIT_CONTRACT CC
LEFT JOIN CTE A ON A.DEBID = CC.DEBID
WHERE CC.CR_CONTRACT_DATE <= '2023-12-31'
AND CC.CR_CONTRACT_END_DATE > '2023-12-31'

--QUÝ 1/2024
--PST = SỐ TIỀN GIẢI NGÂN 
SELECT SUM(CC.CR_AMOUNT) AS PST
FROM CREDIT_CONTRACT CC
WHERE DATEPART(QUARTER, CC.CR_CONTRACT_DATE) = 1 AND YEAR(CC.CR_CONTRACT_DATE) = 2024
--PSG
SELECT SUM(CR.PRINCIPAL_AMOUNT) AS SO_TIEN_GIAM
FROM CUSTOMER_REPAYMENT CR
LEFT JOIN CREDIT_CONTRACT CC ON CC.DEBID = CR.DEBID
WHERE DATEPART(QUARTER, CR.PAYMENT_DATE) = 1 AND YEAR(CR.PAYMENT_DATE) = 2024

--QUÝ 2/2024
--PST = SỐ TIỀN GIẢI NGÂN 
SELECT SUM(CC.CR_AMOUNT) AS PST
FROM CREDIT_CONTRACT CC
WHERE DATEPART(QUARTER, CC.CR_CONTRACT_DATE) = 2 AND YEAR(CC.CR_CONTRACT_DATE) = 2024
--PSG
SELECT SUM(CR.PRINCIPAL_AMOUNT) AS SO_TIEN_GIAM
FROM CUSTOMER_REPAYMENT CR
LEFT JOIN CREDIT_CONTRACT CC ON CC.DEBID = CR.DEBID
WHERE DATEPART(QUARTER, CR.PAYMENT_DATE) = 2 AND YEAR(CR.PAYMENT_DATE) = 2024

--CUỐI KỲ 
WITH CTE AS(
SELECT CR.DEBID, SUM(CR.PRINCIPAL_AMOUNT) AS SO_TIEN_THU
FROM CUSTOMER_REPAYMENT CR
WHERE CR.PAYMENT_DATE <= '2024-06-30'
GROUP BY CR.DEBID)

SELECT SUM(CC.CR_AMOUNT - ISNULL(A.SO_TIEN_THU,0)) FROM CREDIT_CONTRACT CC
LEFT JOIN CTE A ON CC.DEBID = A.DEBID
WHERE CC.CR_CONTRACT_DATE <= '2024-06-30'
AND CC.CR_CONTRACT_END_DATE > '2024-06-30'

------------------------------------------------------------------------------------------------------------------------------------
--TĂNG TRƯỞNG QUA CÁC NĂM
--TỔNG GIÁ TRỊ HDTD (CHƯA TẤT TOÁN)
WITH THU_GOC AS (
    SELECT DEBID, SUM(PRINCIPAL_AMOUNT) AS DA_THU
    FROM CUSTOMER_REPAYMENT
	WHERE PAYMENT_DATE <= '2021-12-31'
    GROUP BY DEBID
)
SELECT SUM(CC.CR_AMOUNT)  AS GIA_TRI_CHUA_TAT_TOAN --TỔNG GIÁ TRỊ HỢP ĐỒNG TÍN DỤNG
FROM CREDIT_CONTRACT CC
LEFT JOIN THU_GOC TG ON CC.DEBID = TG.DEBID
WHERE CC.CR_CONTRACT_DATE <= '2021-12-31'
AND CC.CR_CONTRACT_END_DATE > '2021-12-31'

WITH THU_GOC AS (
    SELECT DEBID, SUM(PRINCIPAL_AMOUNT) AS DA_THU
    FROM CUSTOMER_REPAYMENT
    WHERE YEAR(PAYMENT_DATE) = 2022
    GROUP BY DEBID
)
SELECT SUM(CC.CR_AMOUNT) AS GIA_TRI_CHUA_TAT_TOAN
FROM CREDIT_CONTRACT CC
LEFT JOIN THU_GOC TG ON CC.DEBID = TG.DEBID
WHERE CC.CR_CONTRACT_DATE <= '2022-12-31'
AND CC.CR_CONTRACT_END_DATE > '2022-12-31'

WITH THU_GOC AS (
    SELECT DEBID, SUM(PRINCIPAL_AMOUNT) AS DA_THU
    FROM CUSTOMER_REPAYMENT
    WHERE YEAR(PAYMENT_DATE) = 2023
    GROUP BY DEBID
)
SELECT SUM(CC.CR_AMOUNT) AS GIA_TRI_CHUA_TAT_TOAN
FROM CREDIT_CONTRACT CC
LEFT JOIN THU_GOC TG ON CC.DEBID = TG.DEBID
WHERE CC.CR_CONTRACT_DATE <= '2023-12-31'
AND CC.CR_CONTRACT_END_DATE > '2023-12-31'

-----------------------------------------------------------------------------------------------------------
--TỔNG GIÁ TRỊ TSBĐ (CỦA CÁC HĐ CHƯA TẤT TOÁN)
WITH CTE AS(
SELECT CL.MA_ID, SUM(CL.COL_AMOUNT) AS TONG
FROM CREDIT_CONTRACT CC
INNER JOIN COLLATERALS CL ON CC.MA_ID = CL.MA_ID
INNER JOIN MORTGAGE_AGREEMENT MA ON CL.MA_ID = MA.MA_ID
WHERE CC.CR_CONTRACT_DATE <= '2021-12-31'
AND CC.CR_CONTRACT_END_DATE > '2021-12-31'
group by CL.MA_ID)

SELECT SUM(TONG) FROM CTE A;


WITH CTE AS(
SELECT CL.MA_ID, SUM(CL.COL_AMOUNT) AS TONG
FROM CREDIT_CONTRACT CC
INNER JOIN COLLATERALS CL ON CC.MA_ID = CL.MA_ID
INNER JOIN MORTGAGE_AGREEMENT MA ON CL.MA_ID = MA.MA_ID
WHERE CC.CR_CONTRACT_DATE <= '2022-12-31'
AND CC.CR_CONTRACT_END_DATE > '2022-12-31'
group by CL.MA_ID)

SELECT SUM(TONG) FROM CTE A;


WITH CTE AS(
SELECT CL.MA_ID, SUM(CL.COL_AMOUNT) AS TONG
FROM CREDIT_CONTRACT CC
INNER JOIN COLLATERALS CL ON CC.MA_ID = CL.MA_ID
INNER JOIN MORTGAGE_AGREEMENT MA ON CL.MA_ID = MA.MA_ID
WHERE CC.CR_CONTRACT_DATE <= '2023-12-31'
AND CC.CR_CONTRACT_END_DATE > '2023-12-31'
group by CL.MA_ID)

SELECT SUM(TONG) FROM CTE A