--1. Lập danh sách các hợp đồng tín dụng chưa tất toán tại thời điểm 31/12/2024 theo chi nhánh.
SELECT CB.BRANCH_CODE, CB.BRANCH_NAME, COUNT(CC.CRCONTRACT_ID) AS [SỐ HỢP ĐỒNG CHƯA TÍNH TOÁN] FROM CUSTOMER C
INNER JOIN CREDIT_CONTRACT CC ON C.CUSTID = CC.CUSTID
INNER JOIN CODE_BRANCH CB ON C.BRANCH_CODE = CB.BRANCH_CODE
WHERE CC.CR_CONTRACT_END_DATE > '2024-12-31'--Hợp đồng còn hiệu lực sau ngày này = chưa tính toán
AND CC.CR_CONTRACT_DATE <= '2024-12-31'
GROUP BY CB.BRANCH_CODE, CB.BRANCH_NAME

--2. Lập danh sách các hợp đồng tín dụng sẽ tất toán trong năm 2025 gồm: Mã hợp đồng, số hợp đồng, dư nợ gốc còn lại, lãi phải thu
SELECT CC.MA_ID, COUNT(DISTINCT CC.CRCONTRACT_ID) AS [SỐ HỢP ĐỒNG], SUM(CC.CR_AMOUNT) AS [DƯ NỢ GỐC CÒN LẠI], SUM(DATEDIFF(DAY,CC.CR_CONTRACT_DATE, CC.CR_CONTRACT_END_DATE) / 365.0 * (CC.CR_AMOUNT * CC.CR_INTEREST)) AS[LÃI PHẢI THU] 
FROM CREDIT_CONTRACT CC
WHERE YEAR(CC.CR_CONTRACT_END_DATE) = 2025 
GROUP BY CC.MA_ID

--3. Lập danh sách các hợp đồng tín dụng chưa tất toán tại thời điểm 30/9/2024 của khu vực đông nam bộ.
SELECT CC.CUSTID, CC.MA_ID,CC.CR_CONTRACT_END_DATE,CA.AREA_NAME,CA.AREA_CODE FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON C.CUSTID = CC.CUSTID
INNER JOIN CODE_BRANCH CB ON C.BRANCH_CODE = CB.BRANCH_CODE
INNER JOIN CODE_AREA CA ON CB.AREA_CODE = CA.AREA_CODE
WHERE CC.CR_CONTRACT_END_DATE > '2024-09-30' AND CA.AREA_NAME = 'DONG NAM BO'

--4. Đếm số hợp đồng, tổng tiền giải ngân trong năm 2024 của các hợp đồng phân loại theo danh mục ngành.
SELECT COUNT(CC.CRCONTRACT_ID) AS [SỐ HỢP ĐỒNG], SUM(CC.CR_AMOUNT) AS [TỔNG TIỀN GIẢI NGÂN], CFT.FIN_TYPE_NAME, CFT.FIN_TYPE_CODE FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
INNER JOIN CODE_FIN_TYPE CFT ON C.FIN_TYPE_CODE = CFT.FIN_TYPE_CODE
WHERE YEAR(CC.CR_CONTRACT_DATE) = 2024 
GROUP BY CFT.FIN_TYPE_CODE, CFT.FIN_TYPE_NAME

--5. Đếm số hợp đồng, tổng tiền giải ngân trong năm 2024 của các hợp đồng phân loại theo loại hình doanh nghiệp.
SELECT COUNT(CC.CRCONTRACT_ID) AS [SỐ HỢP ĐỒNG], SUM(CC.CR_AMOUNT) AS [TỔNG TIỀN GIẢI NGÂN], CCT.CUST_TYPE_CODE, CCT.CUST_TYPE_NAME FROM CREDIT_CONTRACT CC
INNER JOIN CUSTOMER C ON CC.CUSTID = C.CUSTID
INNER JOIN CODE_CUST_TYPE CCT ON C.CUST_TYPE_CODE = CCT.CUST_TYPE_CODE
WHERE YEAR(CC.CR_CONTRACT_DATE) = 2024 
GROUP BY CCT.CUST_TYPE_CODE,CCT.CUST_TYPE_NAME

--6. Tính lãi suất tín dụng trung bình theo các năm.
SELECT YEAR(CC.CR_CONTRACT_DATE) AS [NĂM], AVG(CC.CR_INTEREST) AS [LÃI SUẤT TRUNG BÌNH] 
FROM CREDIT_CONTRACT CC
GROUP BY YEAR(CC.CR_CONTRACT_DATE)
ORDER BY [NĂM]

--7. Đếm số lượng hợp đồng, tổng số tiền giải ngân 06 tháng cuối năm 2024 phân loại theo thời hạn: ngắn (dưới 12 tháng) - trung (12-60 tháng) - dài (trên 60).
SELECT 
    COUNT(CC.CR_CONTRACT_DATE) AS [Số hợp đồng],
    SUM(CC.CR_AMOUNT) AS [Tổng giải ngân],
    CASE
        WHEN DATEDIFF(MONTH, CC.CR_CONTRACT_DATE, CC.CR_CONTRACT_END_DATE) < 12 THEN N'NGẮN HẠN'
        WHEN DATEDIFF(MONTH, CC.CR_CONTRACT_DATE, CC.CR_CONTRACT_END_DATE) BETWEEN 12 AND 60 THEN N'TRUNG HẠN'
        ELSE N'DÀI HẠN'
    END AS [THỜI HẠN]
FROM CREDIT_CONTRACT CC 
WHERE CC.CR_CONTRACT_DATE BETWEEN '2024-07-01' AND '2024-12-31'
GROUP BY 
    CASE
        WHEN DATEDIFF(MONTH, CC.CR_CONTRACT_DATE, CC.CR_CONTRACT_END_DATE) < 12 THEN N'NGẮN HẠN'
        WHEN DATEDIFF(MONTH, CC.CR_CONTRACT_DATE, CC.CR_CONTRACT_END_DATE) BETWEEN 12 AND 60 THEN N'TRUNG HẠN'
        ELSE N'DÀI HẠN'
    END

SELECT 
    MIN(CC.CR_CONTRACT_DATE) AS [Ngày sớm nhất],
    MAX(CC.CR_CONTRACT_DATE) AS [Ngày trễ nhất]
FROM CREDIT_CONTRACT CC
-- NGÀY TRỄ NHẤT LÀ THÁNG 6 --> KO CÓ BẢN GHI VỀ 6 THÁNG CUỐI

--8. Đếm số lượng khoản vay, tổng tiền giải ngân và lãi suất trung bình theo các quý trong giai đoạn 2017-2022.
SELECT COUNT(CC.CRCONTRACT_ID) AS[SỐ LG KHOẢN VAY], SUM(CC.CR_AMOUNT)AS[TỔNG TIỀN GIẢI NGÂN], AVG(CC.CR_INTEREST)AS[LÃI SUẤT TB], DATEPART(QUARTER,CC.CR_CONTRACT_DATE) AS [QUÝ], YEAR(CC.CR_CONTRACT_DATE)AS[NĂM] FROM CREDIT_CONTRACT CC
WHERE YEAR(CC.CR_CONTRACT_DATE) BETWEEN 2017 AND 2022
GROUP BY YEAR(CR_CONTRACT_DATE),DATEPART(QUARTER, CR_CONTRACT_DATE)
ORDER BY [NĂM], [QUÝ];

--9. Lập danh sách các hợp đồng tín dụng còn dư nợ (chưa tất toán hết) có nợ gốc còn lại trên 15 tỉ tại thời điểm 30.06.2024.
SELECT 
    CC.CRCONTRACT_ID,
    CC.DEBID,
    SUM(CP.PRINCIPAL_AMOUNT) AS OUTSTANDING_PRINCIPAL
FROM CREDIT_PLAN CP
JOIN CREDIT_CONTRACT CC ON CC.DEBID = CP.DEBID
WHERE CP.END_DATE > '2024-06-30'  -- Gốc chưa đến hạn
GROUP BY CC.CRCONTRACT_ID, CC.DEBID
HAVING SUM(CP.PRINCIPAL_AMOUNT) > 15000000000  -- > 15 tỷ

--10. tính số tiền phải thu (gốc + lãi) theo các tháng từ thời điểm 1/1/2025 đến hết 31/03/2025.
SELECT 
    DATEFROMPARTS(YEAR(CP.END_DATE), MONTH(CP.END_DATE), 1) AS [THÁNG],
    SUM(CP.TOTAL_AMOUNT) AS [TỔNG THU]
FROM CREDIT_PLAN CP
WHERE CP.END_DATE >= '2025-01-01' AND CP.END_DATE <= '2025-03-31'
GROUP BY DATEFROMPARTS(YEAR(CP.END_DATE), MONTH(CP.END_DATE), 1)
ORDER BY [THÁNG]

--11. Xác định lại tổng số dư nợ gốc của các chi nhánh tại thời điểm 31/12/2024.
SELECT CB.BRANCH_NAME, CB.BRANCH_CODE,SUM(CP.PRINCIPAL_AMOUNT) AS [TỔNG DƯ NỢ GỐC] FROM CREDIT_CONTRACT CC
INNER JOIN CREDIT_PLAN CP ON CC.DEBID = CP.DEBID
INNER JOIN CUSTOMER C ON C.CUSTID = CC.CUSTID
INNER JOIN CODE_BRANCH CB ON C.BRANCH_CODE = CB.BRANCH_CODE
WHERE CP.END_DATE > '2024-12-31'
GROUP BY CB.BRANCH_NAME,CB.BRANCH_CODE

--12. Tính tổng số tiền phải thu (gốc, lãi) của mỗi chi nhánh trong 6 tháng đầu năm 2025.
SELECT SUM(CP.TOTAL_AMOUNT) AS[TỔNG THU GỐC + LÃI], CB.BRANCH_NAME,CB.BRANCH_CODE FROM CREDIT_CONTRACT CC
INNER JOIN CREDIT_PLAN CP ON CC.DEBID = CP.DEBID
INNER JOIN CUSTOMER C ON C.CUSTID = CC.CUSTID
INNER JOIN CODE_BRANCH CB ON C.BRANCH_CODE = CB.BRANCH_CODE
WHERE CP.END_DATE BETWEEN '2025-01-01' AND '2025-06-30'
GROUP BY CB.BRANCH_NAME,CB.BRANCH_CODE
