--1: Số tài khoản tiết kiệm đang hoạt động tại 31/12/2023
---> đầu kì
SELECT COUNT(SA.SAVING_ACC_ID) FROM SAVING_ACCOUNT SA 
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE <= '2023-12-31' AND SA.SAVE_END_DATE > '2023-12-31'

--2: Tài khoản mở mới trong năm 2024
-----> PST ---------------
SELECT COUNT(SA.SAVING_ACC_ID) FROM SAVING_ACCOUNT SA 
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE BETWEEN '2024-01-01' AND '2024-12-31'

--3: Số tài khoản đã tất toán trong năm 2024 
----------- phát sinh giảm ------
SELECT COUNT(SA.SAVING_ACC_ID) FROM SAVING_ACCOUNT SA 
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_END_DATE BETWEEN '2024-01-01' AND '2024-12-31'

--4: Số tài khoản tiết kiệm đang hoạt động tại 31/12/2024
---> cuối kì
SELECT COUNT(SA.SAVING_ACC_ID) FROM SAVING_ACCOUNT SA 
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE <= '2024-12-31' AND SA.SAVE_END_DATE > '2024-12-31'---> giống đầu kì và khác mỗi giá trị ngày

--------------------------------------------------------------------------------------------------------------
---> Tổng tiền tk đầu kì
SELECT SUM(SA.SAV_AMOUNT) FROM SAVING_ACCOUNT SA 
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE <= '2023-12-31' AND SA.SAVE_END_DATE > '2023-12-31'

--2: Tổng tiền tk pst trong năm 2024
-----> PST ---------------
SELECT SUM(SA.SAV_AMOUNT) FROM SAVING_ACCOUNT SA 
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE BETWEEN '2024-01-01' AND '2024-12-31'

--3: Tổng tiền tk psg trong năm 2024 
----------- phát sinh giảm ------
SELECT SUM(SA.SAV_AMOUNT) FROM SAVING_ACCOUNT SA 
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_END_DATE BETWEEN '2024-01-01' AND '2024-12-31'

--4: Tổng tiền tk cuối kỳ
---> cuối kì
SELECT SUM(SA.SAV_AMOUNT) FROM SAVING_ACCOUNT SA 
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE <= '2024-12-31' AND SA.SAVE_END_DATE > '2024-12-31'

--------------------------------------------------------------------------------------------------------------
--1:Số lượng khách hàng có tk còn hoạt động tại 31/12/2023
------------- Đếm số khách đầu kì ---------

SELECT COUNT(DISTINCT SA.CUSTID) FROM SAVING_ACCOUNT SA 
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE <= '2023-12-31' AND SA.SAVE_END_DATE > '2023-12-31'

--2:Số lượng khách hàng có tk còn hoạt động trong năm 2024
-----> số khách hàng tăng (khách mới) ==> những khách hàng mở tài khoản trong kì và không có ở đầu kì.
---> những khách hàng mở tài khoản mới.---> loại bỏ những khách hàng đã có ở đầu kì???-- 28
WITH Old_Customers AS --Bảng tạm chứa khách hàng đầu kỳ
(
    SELECT DISTINCT CUSTID
    FROM SAVING_ACCOUNT
    WHERE SAVE_DATE <= '2023-12-31'
    AND SAVE_END_DATE > '2023-12-31'
)

SELECT COUNT(DISTINCT sa.CUSTID) AS New_Customer_Count
FROM SAVING_ACCOUNT SA
WHERE SA.SAVE_DATE BETWEEN '2024-01-01' AND '2024-12-31'
AND SA.CUSTID NOT IN (SELECT CUSTID FROM Old_Customers);

--3:Số lượng khách hàng có tk tất toán trong năm 2024
WITH Still_Customers AS (  --CTE danh sách khách hàng vẫn còn tồn tại trong hệ thống tại thời điểm cuối năm 2024. (cuối kỳ)
    SELECT DISTINCT CUSTID
    FROM SAVING_ACCOUNT
    WHERE SAVE_DATE <= '2024-12-31'
    AND SAVE_END_DATE > '2024-12-31'
)

SELECT COUNT(DISTINCT SA.CUSTID) AS Decreased_Customer_Count
FROM SAVING_ACCOUNT SA
WHERE SA.SAVE_END_DATE BETWEEN '2024-01-01' AND '2024-12-31'
AND SA.CUSTID NOT IN (SELECT DISTINCT CUSTID FROM Still_Customers);

--4:Số lượng khách hàng có tk còn hoạt động cho đến 31/12/2024 (CUỐI KỲ)
SELECT COUNT(DISTINCT SA.CUSTID) FROM SAVING_ACCOUNT SA 
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE SA.SAVE_DATE <= '2024-12-31' AND SA.SAVE_END_DATE > '2024-12-31'

-- 3 khách hàng có tổng tiền gửi tk lớn nhất trong 2024
WITH CTE AS(
SELECT TOP(3) C.CUSTID, C.CUSTNAME, CB.BRANCH_NAME, CTY.CITY_NAME, SUM(SA.SAV_AMOUNT) AS [TỔNG TIỀN], MAX(SA.INTEREST) AS[LÃI SUẤT CAO NHẤT] FROM CUSTOMER C
INNER JOIN SAVING_ACCOUNT SA ON C.CUSTID = SA.CUSTID
INNER JOIN CODE_BRANCH CB ON C.BRANCH_CODE = CB.BRANCH_CODE
INNER JOIN CODE_CITY CTY ON C.ID_CITY = CTY.CITY_CODE
WHERE YEAR(SA.SAVE_DATE) = 2024
GROUP BY C.CUSTID, C.CUSTNAME,CB.BRANCH_NAME, CTY.CITY_NAME
ORDER BY [TỔNG TIỀN] DESC
)
SELECT * FROM CTE

-- Dự kiến các khoản tất toán 06 tháng đầu năm 2025					
SELECT 'Quý I' AS QUY, SUM(SA.TOTAL_VAL) AS [TỔNG TIỀN GỐC PHẢI TRẢ], SUM(SA.INTEREST_VAL) AS [TỔNG LÃI PHẢI TRẢ] FROM CUSTOMER C
INNER JOIN SAVING_ACCOUNT SA ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER, SA.SAVE_END_DATE) = 1 AND (SA.SAV_STATUS = 1 OR SA.WITHDRAW_DAY IS NOT NULL)
UNION
SELECT 'Quý II' AS QUY, SUM(SA.TOTAL_VAL) AS [TỔNG TIỀN GỐC PHẢI TRẢ], SUM(SA.INTEREST_VAL) AS [TỔNG LÃI PHẢI TRẢ] FROM CUSTOMER C
INNER JOIN SAVING_ACCOUNT SA ON C.CUSTID = SA.CUSTID
WHERE DATEPART(QUARTER, SA.SAVE_END_DATE) = 2 AND (SA.SAV_STATUS = 1 OR SA.WITHDRAW_DAY IS NOT NULL)

---LÃI SUẤT BÌNH QUÂN (*LƯU Ý LS BÌNH QUÂN THÌ KO CẦN QUAN TÂM TẤT TOÁN HAY KO)
--<= 2020
SELECT SUM(SA.SAV_AMOUNT * SA.INTEREST) * 1.0 / SUM(SA.SAV_AMOUNT) AS [Lãi suất bình quân trọng số]
FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(YEAR, SA.SAVE_DATE) <= 2020

--2021
SELECT SUM(SA.SAV_AMOUNT * SA.INTEREST) * 1.0 / SUM(SA.SAV_AMOUNT) AS [Lãi suất bình quân trọng số]
FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(YEAR, SA.SAVE_DATE) = 2021

--2022
SELECT SUM(SA.SAV_AMOUNT * SA.INTEREST) * 1.0 / SUM(SA.SAV_AMOUNT) AS [Lãi suất bình quân trọng số]
FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(YEAR, SA.SAVE_DATE) = 2022

--2023
SELECT SUM(SA.SAV_AMOUNT * SA.INTEREST) * 1.0 / SUM(SA.SAV_AMOUNT) AS [Lãi suất bình quân trọng số]
FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(YEAR, SA.SAVE_DATE) = 2023

--2024
SELECT SUM(SA.SAV_AMOUNT * SA.INTEREST) * 1.0 / SUM(SA.SAV_AMOUNT) AS [Lãi suất bình quân trọng số]
FROM SAVING_ACCOUNT SA
INNER JOIN CUSTOMER C ON C.CUSTID = SA.CUSTID
WHERE DATEPART(YEAR, SA.SAVE_DATE) = 2024